### ISSUE TITLE
日付決定

### ISSUE THREAD

**Issue by ysakasin** [kosen10s/lt06docs#1]

**Comment by denari** [comment]
<img width="1029" alt="2016-10-11 20 36 34" src="https://cloud.githubusercontent.com/assets/5387939/19269421/6e4ccecc-8ff5-11e6-9c5c-038fc4f3ff64.png">

hubotの選択に従って、12/3 に開催します。次の開催ではせっかくなのでクソメガネに合わせようというKPTを得た。
