### ISSUE TITLE
たこやきパーチーの準備

### ISSUE THREAD

**Issue by denari** [kosen10s/lt06docs#13]
+ プレートの準備
+ 具材の調査
+ アレルギーや嫌いな食べ物の確認
+ たこ焼き以外の準備(飲み物)

**Comment by ysakasin** [comment]
アレルギー：無し

好みでない食べ物：タコ, イカ, こんにゃく, きのこ　（たこ焼き器の片隅でタコ無し焼きを焼いてたべるぞぉ）

**Comment by tsudukami** [comment]
たこ焼きの材料
- たこ焼き粉
- タコ
- 天かす
- 紅ショウガ
- ネギ
- たこ焼きソース
- 青のり
- かつおぶし
お好みで，こんにゃくやちくわがおいしいとのこと

**Comment by do-su-0805** [comment]
アレルギーはないですが、グレープフレーツが苦手です（グレープフルーツ味のものは好きです

プレートについては、8日くらいまでに決まっていれば9日朝に仕事終わりにヨドバシ梅田で受け取りも可能です。

- 値段は、たこ焼き機だけなら ~5k?くらいなのかな。ホットプレート兼用なら ~15k くらい？

**Comment by denari** [comment]
プレートは実地で買いに走りましょう。
僕は多分到着が遅いので早めにつける人にお願いしたい。

**Comment by denari** [comment]
レシートはとっといてね。

**Comment by do-su-0805** [comment]
僕と酒田くんががんばる？

**Comment by denari** [comment]
頑張れ

**Comment by do-su-0805** [comment]
以下よさげなホットプレート or たこ焼き機、かつヨドバシ京都に在庫がある機種番号を貼るスレとなります。
HGK-12WK-NE

**Comment by do-su-0805** [comment]
KK-00302
安い

**Comment by do-su-0805** [comment]
TIGER
CRC-B300-T 
いいなって思った。
最初のHGK- … は安いけど製造が2009 年だし、
KK-00302 に 5k だすくらいならこれに 12k 出すわ。

もう少し募集しておきますが、きっと現地でこれを買います。
