### ISSUE TITLE
会場手配

### ISSUE THREAD

**Issue by ysakasin** [kosen10s/lt06docs#2]

**Comment by denari** [comment]
たこ焼きできるところにするか否か

**Comment by denari** [comment]
# 法雲寺会館 多目的スペース
- スーパーが近いのと、業務スーパーが行けそう
- ネットはある
- バスでのアクセス以外が厳しそう
- 費用は1時間2000円

```
※ バスについて
日中(9:00 - 18:00)は10分に一本、他の時間は20分に一本ペース
京都駅からもバスがでる。終バスは京都駅→寺が22:57 寺→京都駅が22:13
```

## ざっくり案まとめ (by つづかみ)

公共の会議室→二次会たこ焼きの店
ゲストハウスやギークハウス、寺などで焼いたりltしたり

**Comment by denari** [comment]
つづ神が法雲寺会館を抑えてくれたのでclose
