### ISSUE TITLE
タイムスケジュール作成

### ISSUE THREAD

**Issue by ysakasin** [kosen10s/lt06docs#3]

**Comment by denari** [comment]
昼にぶらりと観光を挟み、夕方に寺LT、すこし遅めのパーティーをしてミイラになりたい。朝は任意。

**Comment by denari** [comment]
17-21 :: 寺

**Comment by e10dokup** [comment]
@NKMR6194 が早朝深夜バス芸キメるらしいので可能な限り早く来れるやつから順次集合 - 14:00つづかみ到着ということで全員集合というのはどうでしょう

**Comment by denari** [comment]
14時以前の予定は組まない感じで。14時に京都駅集合は確定。それ以前の予定はキッチリ決めずにSlackとかで適当に連絡とり合いながらわいわいしましょう

**Comment by denari** [comment]
14時 - 16時 清水らへん観光
16時 - 17時 移動andたこ焼き具材買い出し
17時 - 21時 LTしながらしゃべりながらタコを焼き京都を燃やす
21時解散 ミイラ化するひとはdo_suに引き渡し
